[package]
name = "thumbhash-pyrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "thumbhash_pyrust"
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
pyo3 = "0.21.1"
thumbhash = "0.1.0"
